import random

names = [
    'Nona Leonard',
    'Everett Olsen',
    'Spencer Howard',
    'Martha Russo',
    'Jerome Henderson',
    'Refugio Hurley',
    'Glen Dillon',
    'Gerald Yoder',
    'Ismael Villegas',
    'Eileen Soto',
    'Gus Porter',
    'Roberto Choi',
    'Lucile Clark',
    'Jane Barton',
    'Rachelle Short',
    'Faustino Leach',
    'Tyron Armstrong',
    'Flora Meyers',
    'Darrell Huff',
    'Noel Wheeler',
    'Winfred Maddox',
    'Man Fields',
    'Bud Williamson',
    'Lizzie Floyd',
    'Alejandro Roberts',
    'Cristobal Sawyer',
    'Courtney Morales',
    'Marcos Booker',
    'Nathan Mcbride',
    'Helena Wade',
    'Stanton Atkins',
    'Marshall Huerta',
    'Ahmed Aguirre',
    'Bryant Estes',
    'Bernice Frost',
    'Adela Hatfield',
    'Alma Villa',
    'Amber Logan',
    'Donald Bowen',
    'Rickie Chavez',
    'Jarrett Hodge',
    'Morris Fleming',
    'Emma Fritz',
    'Carlton Kent',
    'Kieth Kane',
    'Roy Alvarez',
    'Allan Zavala',
    'Lupe Hayes',
    'Camille Dominguez',
    'Tracy Powell',
]


def get_random() -> str:
    return random.choice(names)
